---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/deployment.yaml
  - ./resources/pdb.yaml
  - ./resources/service.yaml


transformers:
  - ./transformers/label.yaml


images:
  - name: patrickdk/redis-sentinel-proxy
    # newName: patrickdk/redis-sentinel-proxy
    newTag: latest
